name: Test Env Secrets

on:
  workflow_dispatch:   # manual trigger so you can test anytime

jobs:
  test-env:
    runs-on: ubuntu-latest
    environment: preprod   # change to `production` to test prod secrets
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Create .env.local
        run: |
          echo "NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}" > .env.local
          echo "CLIENT_ID=${{ secrets.CLIENT_ID }}" >> .env.local
          echo "PROJECT_ID=${{ secrets.PROJECT_ID }}" >> .env.local
          cat .env.local

      - name: Show partial secrets from .env.local
        run: |
              NEXTAUTH_SECRET=$(grep ^NEXTAUTH_SECRET .env.local | cut -d '=' -f2)
              CLIENT_ID=$(grep ^CLIENT_ID .env.local | cut -d '=' -f2)
              PROJECT_ID=$(grep ^PROJECT_ID .env.local | cut -d '=' -f2)

              echo "NEXTAUTH_SECRET ends with: ${NEXTAUTH_SECRET: -4}"
              echo "CLIENT_ID ends with: ${CLIENT_ID: -4}"
              echo "PROJECT_ID ends with: ${PROJECT_ID: -4}"



