name: Test Env Secrets

on:
  workflow_dispatch:   # manual trigger so you can test anytime

jobs:
  test-env:
    runs-on: ubuntu-latest
    environment: prod   # change to `production` to test prod secrets
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Create .env.local
        run: |
          echo "NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}" > .env.local
          echo "CLIENT_ID=${{ secrets.CLIENT_ID }}" >> .env.local
          echo "PROJECT_ID=${{ secrets.PROJECT_ID }}" >> .env.local
          cat .env.local
